### ISSUE TITLE
Camera not usable

### ISSUE THREAD

**Issue by Ninlives** [XayahSuSuSu/device_xiaomi_cmi#1]
I compile the lineageos for cmi using this device tree and vendor blob extracted from stock rom v12.5.7. There is no camera app installed in the rom, and apps like Alipay cannot use camera. Is this a known issue? I synced the manifest of official LineageOS using lineage-18.1 branch, and add this devices tree to `device/xiaomi/cmi`, and cloned `hardware/xiaomi`, `kernel/xiaomi/sm8250` from official repo, did I miss any dependencies?

**Comment by XayahSuSuSu** [comment]
> I compile the lineageos for cmi using this device tree and vendor blob extracted from stock rom v12.5.7. There is no camera app installed in the rom, and apps like Alipay cannot use camera. Is this a known issue? I synced the manifest of official LineageOS using lineage-18.1 branch, and add this devices tree to `device/xiaomi/cmi`, and cloned `hardware/xiaomi`, `kernel/xiaomi/sm8250` from official repo, did I miss any dependencies?

Weird. It sholud work, 'cause it works on Havoc

**Comment by Ninlives** [comment]
`adb logcat` reports needed shared object not found, I'm trying to add them and testing. Is there a way to quickly add files to /vendor/lib without repacking the entire rom?

**Comment by XayahSuSuSu** [comment]
> `adb logcat` reports needed shared object not found, I'm trying to add them and testing. Is there a way to quickly add files to /vendor/lib without repacking the entire rom?

You can repack the rom or just make a magisk module

**Comment by Ninlives** [comment]
These files are needed to make camera work on my build:
```
vendor/lib/libmegface.so
vendor/lib/libMegviiFacepp-0.5.2.so
vendor/lib64/libmegface.so
vendor/lib64/libMegviiFacepp-0.5.2.so
vendor/lib64/libst_soft_isp_calc_exposure_shared.so
vendor/lib64/libmulticam_image_optical_zoom.so
vendor/lib64/libst_soft_isp_shared.so
```

**Comment by XayahSuSuSu** [comment]
> These files are needed to make camera work on my build:
> 
> ```
> vendor/lib/libmegface.so
> vendor/lib/libMegviiFacepp-0.5.2.so
> vendor/lib64/libmegface.so
> vendor/lib64/libMegviiFacepp-0.5.2.so
> vendor/lib64/libst_soft_isp_calc_exposure_shared.so
> vendor/lib64/libmulticam_image_optical_zoom.so
> vendor/lib64/libst_soft_isp_shared.so
> ```

Nice work!
